version: '0.82.0-{build}'
image: Visual Studio 2015

environment:
  matrix:
  - COMPILER_NAME: mingw-w64-7.3.0-qt5-13
    QT: C:\Qt\5.13\mingw73_64
    MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    
  - COMPILER_NAME: mingw-w64-7.3.0-qt5-12
    QT: C:\Qt\5.12\mingw73_64
    MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    
  - COMPILER_NAME: mingw-32-5.3.0-qt5-9
    QT: C:\Qt\5.9.7\mingw53_32
    MINGW_DIR: C:\MinGW\bin

init:
  - cmd: set PATH=%MINGW_DIR%;%PATH%
  - cmd: set PATH=%QT%\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: dir %MINGW_DIR%

install:
  - cinst yasm
  - cmd: call download-sources.bat
  
configuration:
  - Release
  
build_script:
  - cmd: call build-all.bat
  
after_build:
  - cmd: call package-artifacts.bat
  
test_script:
  - cmd: call run-tests.bat
  
artifacts:
  - path: release\poppler-%COMPILER_NAME%.zip
    name: taglib-%COMPILER_NAME%
