TAGLIB_VERSION: 0.82.0

version: '{TAGLIB_VERSION}-{build}'
image: Visual Studio 2015

environment:
  matrix:
  - COMPILER_NAME: mingw-w64-8.1.0
    MINGW_DIR: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
    
  - COMPILER_NAME: mingw-w64-7.3.0
    MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    
  - COMPILER_NAME: mingw-w64-7.2.0
    MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
    
  - COMPILER_NAME: mingw-w64-6.3.0
    MINGW_DIR: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
    
  - COMPILER_NAME: mingw-32-5.3.0
    MINGW_DIR: C:\MinGW\bin

init:
  - cmd: set PATH=%MINGW_DIR%;%PATH%
  - cmd: echo %PATH%
  - cmd: dir %MINGW_DIR%

install:
  - cinst yasm
  - cmd: call download-sources.bat
  
configuration:
  - Release
  
build_script:
  - cmd: call build-all.bat
  
after_build:
  - cmd: call package-artifacts.bat
  
artifacts:
  - path: release\poppler-%COMPILER_NAME%.zip
    name: taglib-%COMPILER_NAME%