version: '0.87.0-{build}'
image: Visual Studio 2015

environment:
  matrix:
  - COMPILER_NAME: mingw-w64-7.3.0-qt5-14
    QT: C:\Qt\5.14\mingw73_64
    MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    MINGW_VERSION: 730_64
  
  - COMPILER_NAME: mingw-w64-7.3.0-qt5-13
    QT: C:\Qt\5.13\mingw73_64
    MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    MINGW_VERSION: 730_64
    
  - COMPILER_NAME: mingw-w64-7.3.0-qt5-12
    QT: C:\Qt\5.12\mingw73_64
    MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    MINGW_VERSION: 730_64
    
  - COMPILER_NAME: mingw-32-7.3.0-qt5-12
    QT: C:\Qt\5.12\mingw73_32
    MINGW_DIR: C:\Qt\Tools\mingw730_32\bin
    MINGW_VERSION: 730_32
    
  - COMPILER_NAME: mingw-32-5.3.0-qt5-9
    QT: C:\Qt\5.9\mingw53_32
    MINGW_DIR: C:\MinGW\bin
    MINGW_VERSION: 530_32

init:
  - cmd: set PATH=%MINGW_DIR%;%PATH%
  - cmd: set PATH=%QT%\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: dir %MINGW_DIR%
  - cmd: set CMAKE_PREFIX_PATH=%QT%

install:
  - cinst yasm
  - cmd: dir
  - cmd: call download-all.bat
  
configuration:
  - Release
  
build_script:
  - cmd: dir
  - cmd: call build-all.bat
  
after_build:
  - cmd: dir
  - cmd: call package-artifacts.bat
  
test_script:
  - cmd: dir
  - cmd: call run-tests.bat
  
artifacts:
  - path: release\poppler-%COMPILER_NAME%.zip
    name: taglib-%COMPILER_NAME%
